#!/bin/sh

#resolucao horizontal
resolucao_horizontal="$(LANG=C xdpyinfo  | grep 'dimensions:' | sed 's|.*dimensions: *||g;s|x.*||g')"

if [ "$(grep "$resolucao_horizontal" ~/.config/plasmashellrc)" = "" ]; then
    echo "[PlasmaViews][Panel 2][Horizontal$resolucao_horizontal]
thickness=44" >> ~/.config/plasmashellrc
fi 
